language: python
services: sqlite
env:
    - DJANGO_VERSION=1.4.10
    - DJANGO_VERSION=1.5.6
    - DJANGO_VERSION=1.6
python:
    - "3.3"
    - "2.7"
    - "2.6"
install:
    - "pip install -q django==$DJANGO_VERSION"
    - "python setup.py -q install"
    - "pip install -r requirements.txt"
script: "py.test tests/"
matrix:
    exclude:
        - python: 3.3
          env: DJANGO_VERSION=1.4.10
